### ISSUE TITLE
Publish to Bonsai

### ISSUE THREAD

**Issue by jaredledvina** [belak/sensu-go-tools#2]
@belak - Any thoughts on publishing the IRC handler to https://bonsai.sensu.io/ ?

https://github.com/sensu/sensu-influxdb-handler is an handler that currently does this + uses https://github.com/goreleaser/goreleaser to cross-compile. 

If you're cool with it, I think the most straightforward setup would be to move the irc handler into dedicated repo (or just rename this one). 

I'm game to help out get it all configured properly, let me know if you'd like to do this!

**Comment by belak** [comment]
Alright, done. I've created a new github org (sensu-utils), a new repo (sensu-irc-handler), and renamed this to be a library which is used by sensu-irc-handler. I tried to mimic the build infrastructure used by sensu-influxdb-handler and sensu-slack-handler. Let me know if there's anything else that needs to be done.

**Comment by jaredledvina** [comment]
Oh wow, that was really fast. I hope you got some sleep last night 😄 

Looks great to me, I'll try to help out as time allows.
